# Connection Details
set SHARED_ACCESS_KEY_NAME=iothubowner
set DEVICE_NAME= 
set IOTHUB_DEVICE_CONN_STRING= 
set IOTHUB_CONN_STRING_CSHARP=
set SERVICE_CONNECTION_STRING=
set DEVICE_ID= 
set EVENT_HUBS_COMPATIBILITY_ENDPOINT= 
set EVENT_HUBS_COMPATIBILITY_PATH=myhub137
set EVENT_HUBS_SAS_KEY= 
set EVENT_HUBS_CONNECTION_STRING=